name: Update Notebooks And Refresh Page
on:
  schedule:
    - cron:  '23 2 * * *'

jobs:
  update-notebooks:
    if: github.event_name == 'schedule' 
    runs-on: ubuntu-latest
    steps:
  
    - name: See event name
      run: |
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}

    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get -y --force-yes install chromium-chromedriver
        npm install -g electron@6.1.4 orca
        pip3 install matplotlib pandas numpy scipy seaborn papermill ipykernel jupyter folium plotly plotnine psutil pymc3 arviz xlrd altair altair_saver jinja2 selenium
        python3 -m ipykernel install --user --name python3
        sudo chmod -R 777 .
        
    - name: update notebooks
      id: update_nb
      run: |
        ./_action_files/run_notebooks.sh

    - name: Create an issue if notebook update failure occurs
      if: github.event_name == 'schedule' && steps.update_nb.outputs.error_bool == 'true'
      uses: actions/github-script@0.6.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var err = process.env.ERROR_STRING;
          var run_id = process.env.RUN_ID;
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Error updating notebooks",
            body: `These are the notebooks that failed to update properly: \n${err}\n\n See run [${run_id}](https://github.com/github/covid19-dashboard/actions/runs/${run_id}) for more details.`
          })
      env:
        ERROR_STRING: ${{ steps.update_nb.outputs.error_str }}
        RUN_ID: ${{ github.run_id	 }}

    - name: save notebooks & images
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -m'[bot] refresh notebooks'
        git push -f
    
    - name: Comment on issue if failure in updating notebooks
      if: github.event_name == 'issues' && steps.update_nb.outputs.error_bool == 'true'
      uses: actions/github-script@0.6.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var run_id = process.env.RUN_ID;
          var err = process.env.ERROR_STRING;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `An error occurred when attempting to refresh one or more of the notebooks in run [${run_id}](https://github.com/github/covid19-dashboard/actions/runs/${run_id}). These are the notebooks that failed to update properly: \n${err}`
          })
      env:
        ERROR_STRING: ${{ steps.update_nb.outputs.error_str }}
        RUN_ID: ${{ github.run_id	 }}
  
    - name: Comment on issue if failure in workflow
      if: failure() && github.event_name == 'issues'
      uses: actions/github-script@0.6.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var run_id = process.env.RUN_ID;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `An workflow error occurred in run [${run_id}](https://github.com/github/covid19-dashboard/actions/runs/${run_id}) when attempting to refresh the notebooks.`
          })
      env:
        RUN_ID: ${{ github.run_id	 }}

    - name: Comment on and close issue if successful
      if: github.event_name == 'issues' && steps.update_nb.outputs.error_bool == 'false'
      uses: actions/github-script@0.6.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'All notebooks updated successfully.'
          })
          github.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          })
